# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c99424c2f84a1f8c848b8584b2b005464edcdd9d3ccbc1dd7146676cc97d190a7d4aef228d14db7e3dcfda00f580d7bd816e634d48247bdbee71b6c6f755f6f7

test:
  secret_key_base: aa6ddcc9ac5cdfa6058e5b23538fa27bd65f5ae48ad7cff6cb23bdee88eba2303ce738dcd48bb5144f9283afe3fb835a31693585192742f9eccb8a755accb161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
